#!/usr/bin/env python3
# -*- coding: utf-8 -*-

""""""

__all__ = ['__version__', '__date__', '__commit__']


__version__ = '0.0.0'
__date__ = 'yyyy-mm-dd'
__commit__ = ''


if __name__ == '__main__':
    pass
